name: $(Major).$(Minor)$(rev:.r)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(BuildConfiguration)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: EsrpCodeSigning@5
  inputs:
    ConnectedServiceName: '$(ConnectedServiceName)'
    AppRegistrationClientId: '$(EsrpAppRegistrationClientId)'
    AppRegistrationTenantId: '$(EsrpAppRegistrationTenantId)'
    AuthAKVName: '$(EsrpKeyVault)'
    AuthCertName: '$(EsrpCertName)'
    AuthSignCertName: '$(EsrpSignCertName)'
    FolderPath: 'src'
    Pattern: '*.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "keyCode": "CP-230856",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
    PendingAnalysisWaitTimeoutMinutes: '5'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    versioningScheme: 'byBuildNumber'

- task: EsrpCodeSigning@5
  inputs:
    ConnectedServiceName: '$(ConnectedServiceName)'
    AppRegistrationClientId: '$(EsrpAppRegistrationClientId)'
    AppRegistrationTenantId: '$(EsrpAppRegistrationTenantId)'
    AuthAKVName: '$(EsrpKeyVault)'
    AuthCertName: '$(EsrpCertName)'
    AuthSignCertName: '$(EsrpSignCertName)'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    Pattern: '*.nupkg'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
    PendingAnalysisWaitTimeoutMinutes: '5'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src'
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
